# Generated by Django 5.2.7 on 2025-10-05 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentName', models.CharField(max_length=100, null=True)),
                ('DepartmentLocation', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorName', models.CharField(max_length=100, null=True)),
                ('Specialization', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('department', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.departmentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientName', models.CharField(max_length=100, null=True)),
                ('Age', models.CharField(max_length=100, null=True)),
                ('Gender', models.CharField(max_length=100, null=True)),
                ('Phone', models.EmailField(max_length=100, null=True)),
                ('Address', models.TextField(max_length=100, null=True)),
                ('doctor', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.doctormodel')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(null=True)),
                ('status', models.CharField(default='Pending', max_length=100, null=True)),
                ('doctor', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.doctormodel')),
                ('patient', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.patientmodel')),
            ],
        ),
    ]
