# Generated by Django 5.2.7 on 2025-10-05 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientmodel',
            old_name='Phone',
            new_name='email',
        ),
    ]
