# Generated by Django 5.2.7 on 2025-10-05 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_rename_phone_patientmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='department',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='myApp.departmentmodel'),
        ),
    ]
