# Generated by Django 5.2.7 on 2025-10-05 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_doctormodel_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctormodel',
            name='department',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_department', to='myApp.departmentmodel'),
        ),
    ]
