# Generated by Django 5.2.7 on 2025-10-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_doctormodel_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentmodel',
            name='DepartmentLocation',
        ),
        migrations.AddField(
            model_name='departmentmodel',
            name='DepartmentAddress',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
