# Generated by Django 5.2.7 on 2025-10-05 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_remove_departmentmodel_departmentlocation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentmodel',
            old_name='DepartmentAddress',
            new_name='DepartmentDescription',
        ),
    ]
