# Generated by Django 5.2.7 on 2025-10-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_rename_departmentaddress_departmentmodel_departmentdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormodel',
            name='doctor_image',
            field=models.ImageField(null=True, upload_to='Media/Doctor_Picture'),
        ),
    ]
